language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest tests -vv
deploy:
  provider: heroku
  api_key:
    secure: nHKKoy9bFYRRaH+zhh5i9K2LtWSgq98FskwTG6LmNV9X2tPqJnZkZBsv0OEPIhPCu5a1PX1ktN04Kv4l+PZk+iEOcLBTCYrK/gz7dBj+vy0yC/7veEAZcbcEvc2sa+mER4gYHb209kXUYEfidyWly8kzezkrtOiCTQ/lcJGqsLdRebLPt/4W25q4fH72Tgqw9W2UmTfNa+eGe7NpZi3a3kz9PxsKi5Y7CmLD9TPo5EodOGA6NYo1ME5c7+0PREsvXawsZfE5Dut/fdGbSz7tTvDM3PRqz+rcZ6mLJstjzoqkjirtEsZBjsHCmf0t3JhERNaoHU/STbBVuKOOrESMhpSzjbb6tX6gB8h5C5TbzPmxvQzUw+oBUxPnG5TdTEBlNboDGaYvTXOq3a71ag4aXgPNXlwZ5emRb2IowDhqavqyTxtLI+UG3zTrAXqh+YSapU/fQPEhAxwE70pJD3kPsyT/QZPxllMZD9GNsyjmYHMi1Mp8R7gHuwoi4CM7hWFLJSoI9LGV+uZ8tWX1l6mQU0wyadOvWNbr0o02bdFcJKlfZsGCJjyYhuBzBoWs8lDu5bUDJngh4xWlsKEbLVWZq7oJEDCcRpt9xhLJ2kN+qUCMYZmOLSII2vKo/WW11WlkpoBzJ5k36VQfUIBZ638FUJ+8iE8u9OXG9Sp7zb+ycPc=
  app: eddie-yuber
  on:
    repo: dhachuel/eddie-van-hailing
