language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest tests -vv
deploy:
  provider: heroku
  api_key:
    secure: Xq0U4Dh09Q2zo3yxgUKCDUI1srzFphP+OQ9bXzDIQh4OerWJFPVkorTFg9G3FX6H5u5V6jwfiOAqzY4Vq5mlpCD8iYLaNySjKebBvwtTVoy9KngcakX/TyVY/PW9lytPW0LDevFxQRwybgYTGOlSwziMdxmc27afTlOoXgQ/2PHPStBBUGfzyx2KpIIS+5sCdr9+apKeEXdjJla7O9MEw7mpBp7slP+oC18PIuGv/AtT9GlqXNPQ/DUhnjvKW8wyZqAVbL3BwtipTpdRo5bh54KS61G0JaExPB8d4jKD4rh77KH1Kzk31HnBo3I1Rx3dk5td1f+w7894+WGQk1UiHgUX1+LdmspeT5NmGU1zJE2Y0hFA3x6D9VEeD7WpBtBH4gAI0dQq0TJGWHp77lIcF4WL/8Ol70f2cRrkzsiT0qHzEzUJnnlaEJU/nVgw6i61mpSlGEGfS4T3MtqnJ45HzwO4rQcds4HpFzVsOZlUcimAjkoEvjRd8Wp4d5PdehlYIHAPHjmHMaC19Rf5isj418agqWAvvDtrRY6GNJwB0jaGfc3qNfPCNy0HSx+fnfaBNenzA8KA1N+7636uGB+vf0yrmYHndgfA3ym/c988MH0zPJTaSp5DI8lBH4/5RbZ2Ll6FF9hAZm7dKnywl4zR2K8dRr8s9ko3ovo0K0x4yIk=
  app: 'yes'
  on:
    repo: dhachuel/eddie-van-hailing
