FORMAT: 1A

# The VanHailing API
VanHailing lets you request vans for personal use, from moving furniture to 


# /quote
This resource is in charge of determining pricing for trips. 


## GET

+ Response 200 (text/plain)

        Hello World!

## POST
OK, let's add another action. This time to put new data to our resource
(essentially an update action).

+ Request (application/json)

        {
            "rider_id": "58d7875b-40f1-4cab-b650-bfc972bb8a46",
            "pickup_location":{
                "lat": 40.7246704,
                "long": -73.9918311
            },
            "dropoff_location":{
                "lat": 40.759155474313346,
                "long": -73.95326614379883
            },
            "pickup_datetime": "2017-11-16 15:42:49.440762-05:00"
        }

+ Response 202













